djangoProject_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('project.urls')),
    path('', include('skills.urls')),
    path('', include('resume.urls')),
    path('', include('experience.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('contact.urls')),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

skills/urls.py
from django.urls import path

from skills import views

urlpatterns = [
    path('create-skill/', views.SkillsCreateView.as_view(), name='create_skill'),
    path('list-of-skills/', views.SkillsListView.as_view(), name='list_of_skills'),
    path('update-skill/<int:pk>', views.SkillsUpdateView.as_view(), name='update_skill'),
    path('delete-skill/<int:pk>', views.SkillsDeleteView.as_view(), name='delete_skill')
]

skills/models.py
from django.db import models


class Skills(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updates_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.description}'

skills/forms.py
from django import forms
from django.forms import TextInput, Textarea

from skills.models import Skills


class SkillsForm(forms.ModelForm):
    class Meta:
        model = Skills
        fields = ['name', 'description']
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please write the name of the skill!', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'Please enter a description!', 'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        get_name = cleaned_data.get('name')
        all_skills = Skills.objects.all()
        for skill in all_skills:
            if get_name == skill.name:
                msg = 'There si already a skill with this name added in our database!'
                self._errors['name'] = self.error_class([msg])

        return cleaned_data


class SkillsUpdateForm(forms.ModelForm):
    class Meta:
        model = Skills
        fields = ['name', 'description']
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please write the name of the skill!', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'Please enter a description!', 'class': 'form-control'})
        }

skills/views.py
# from django.shortcuts import render
# import requests
import requests
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from skills.forms import SkillsForm, SkillsUpdateForm
from skills.models import Skills


class SkillsCreateView(CreateView, PermissionRequiredMixin):
    template_name = 'skills/create_skill.html'
    model = Skills
    form_class = SkillsForm
    success_url = reverse_lazy('list_of_skills')
    permission_required = 'skills.create_skills'


class SkillsListView(ListView):
    template_name = 'skills/list_of_skills.html'
    model = Skills
    context_object_name = 'all_skills'

    def get_context_data(self, **kwargs):
        context = super(SkillsListView, self).get_context_data(**kwargs)
        all_skills = Skills.objects.all()
        context['all-skills'] = all_skills

        return context


class SkillsUpdateView(UpdateView, PermissionRequiredMixin):
    template_name = 'skills/update_skill.html'
    model = Skills
    form_class = SkillsUpdateForm
    success_url = reverse_lazy('list_of_skills')
    permission_required = 'skills.update_skills'


class SkillsDeleteView(DeleteView, PermissionRequiredMixin):
    template_name = 'skills/delete_skill.html'
    model = Skills
    success_url = reverse_lazy('list_of_skills')
    permission_required = 'skills.delete_skills'


@permission_required('skills.delete_skills')
def delete_project(request, pk):
    Skills.objects.filter(id=pk).delete()
    return redirect('list_of_skills')

templates/skills/create_skill.html
{% extends 'base.html' %}
{% block title %} Add a new Skill {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card-header"><h4 class="text-center text-white"><b>Add a new skill</b></h4></div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body text-white">
                            {{ form.as_table }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success btn-lg">Save</button>
                        </div>
                    </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/skills/delete_skill.html
{% extends 'base.html' %}
{% block title %}Delete {{ skill.name }} {% endblock %}
{% block content %}
    <div class="container"><br><br><br>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <h3 class="text-center"> Are you sure you want to delete {{ skill.name }}?</h3>
                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <a href="{% url 'list_of_skills' %}" class="btn btn-secondary">No</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/skills/list_of_skills.html
{% extends 'base.html' %}
{% block title %} List of Skills {% endblock %}
{% block content %}
    <section class="p-5">
        <div class="container">
            <div class="row text-center g-4">
                <div class="col-md">
                    {% if all_skills %}
                        <div class="row row-cols-2 row-cols-md-r g-4">
                        {% for skill in all_skills %}
                            <div class="card bg-dark text-light">
                                <div class="card-header"><h5
                                        class="card-title text-center text-white">{{ skill.name }}</h5>
                                </div>
                                <div class="card-body">
                                    <ul class="card-text text-white">
                                        <li> {{ skill.description }}</li>

                                    </ul>
                                    <div class="dropdown text-center">
                                        <button class="btn btn-outline-secondary dropdown-toggle text-white"
                                                type="button"
                                                id="dropdownMenuButton1"
                                                data-bs-toggle="dropdown" aria-expanded="false">Actions
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            {% if perms.skills.view_skills %}
                                                <li><a href="{% url 'update_skill' skill.id %}"
                                                       class="dropdown-item">Update</a>
                                            {% endif %}
                                            </li>
                                            {% if perms.skills.delete_skills %}
                                                <li><a href="{% url 'delete_skill' skill.id %}"
                                                       class="dropdown-item">Delete</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/skills/update_skill.html
{% extends 'base.html' %}
{% block title %} Update Skill {% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card text-bg-dark mb3" style="max-width: 40rem;">
                    <div class="card-header text-center"><h4>Update Skill</h4></div>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}